use_default_settings: true

general:
  instance_name: "watchit-searxng"

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  secret_key: "watchit-dev-secret-key-change-me"
  limiter: false
  image_proxy: true
